---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: running-cronjob
spec:
  # Time is measured in coordinated universal time (UTC)
  #          ┌───────────── minute (0 - 59)
  #          │ ┌───────────── hour (0 - 23)
  #          │ │ ┌───────────── day of the month (1 - 31)
  #          │ │ │ ┌───────────── month (1 - 12)
  #          │ │ │ │ ┌───────────── day of the week (0 - 6) (Sunday to Saturday;
  schedule: "0 13 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: hibernator
          containers:
          - name: worker
            image: quay.io/jpacker/hibernation-curator:latest
            command: ['python','action.py']
            env:
            - name: TAKE_ACTION
              value: Running
            - name: PYTHONWARNINGS
              value: "ignore:Unverified HTTPS request"  
          restartPolicy: OnFailure
